version: '2'
services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php/
    env_file: .env
    environment:
      - MYSQL_HOSTMAME=db
    depends_on:
      - db
    ports:
      - 9000:9000
    volumes:
      - ./php:/code/
  db:
    image: mysql:latest
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
